<?xml version="1.0"?>

<!-- Задача 1: Свържете и валидирайте дадения по-долу XML документ с дадената DTD граматика по следните 2 начина:-->
<!-- Вътрешно DTD-->

<!-- Създаваме вътрешно DTD за xml файла с root елемент shiporder.-->
<!DOCTYPE shiporder[
<!-- Декларираме елемент shiporder, който има поделементи orderperson, shipto и item,
като елементът item може да се среща 1 или повече пъти.-->
<!ELEMENT shiporder (orderperson,shipto,item+)>
<!-- Декларираме атрибут orderid на елемента shiporder, който е задължителен и е от тип CDATA.-->
<!ATTLIST shiporder orderid CDATA #REQUIRED>
<!-- Декларираме елемент orderperson.-->
<!ELEMENT orderperson (#PCDATA)>
<!-- Декларираме елемент shipto, който има поделементи name, address, city, country.-->
<!ELEMENT shipto (name,address,city,country)>
<!-- Декларираме елементите name, address, city, country.-->
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!-- Декларираме елемента item, който има поделементи title, note, quantity и price, 
като елементът note може да се среща 0 или 1 пъти.-->
<!ELEMENT item (title,note?,quantity,price)>
<!-- Декларираме елементите title, note, quantity и price.-->
<!ELEMENT title (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>

<!-- XML документа от условието на задачата.-->
<shiporder orderid="889923">
   <orderperson>John Smith</orderperson>
   <shipto>
       <name>Ola Nordmann</name>
       <address>Langgt 23</address>
       <city>4000 Stavanger </city>
       <country> Norway </country>
   </shipto>
   <item>
       <title>Empire Burlesque</title>
       <note>Special Edition</note>
       <quantity>1</quantity>
       <price>10.90</price>
   </item>
   <item>
       <title>Hide your heart</title>
       <quantity>1</quantity>
       <price>9.90</price>
   </item>
</shiporder>